site_name: 'Jenkins Pipeline'

pages:
- Introduction: 'index.md'
- Contents: 'intro.md'
- Problem Statement: 'problem_statement.md'
- Glossary: 'glossary.md'
- Setting Up VMs: 'setting_up_vms.md'
- Setting Up Pipeline: setting_up_pipeline.md
- Static Analysis: 'static_analysis.md'
- Comparing SAST Tools: 'comparing_sast_tools.md'
- Configuring Webhook: 'configuring_webhook.md'
- Deploying the Report: 'deploying_report.md'
- Dynamic Analysis: 'dynamic_analysis.md'
- Comparing DAST Tools: 'comparing_dast_tools.md'
- Code Quality Analysis: 'code_quality_analysis.md'
- Generating Software Bill of Materials: 'generating_sbom.md'
- Final Pipeline Structure: 'final_pipeline.md'
- Shifting Local Setup to AWS: 'moving_setup_to_aws.md'
- Secrets Management: 'secrets_management.md'
- Limitations: 'limitations.md'
- Resources: 'resources.md'


theme: material