site_name: 'Jenkins Pipeline'

pages:
- Introduction: 'index.md'
- Problem Statement: 'problem_statement.md'
- Glossary: 'glossary.md'
- Setting Up VMs: 'setting_up_vms.md'
- Static Analysis: 'static_analysis.md'
- Comparing SAST Tools: comparing_sast_tools.md
- Setting Up Pipeline: setting_up_pipeline.md
- Configuring Webhook: configuring_webhook.md
- Deploying the Report: deploying_report.md
- Resources: resources.md


theme: material