name: Identifying Secrets in the Repository with git-secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
#    - name: Set up Python 3.x
#      uses: actions/setup-python@v1
#      with:
#        python-version: '3.x'

#    - name: Install TruffleHog on the Runner
#      run: |
#        pip install trufflehog
#     - name: trufflehog-actions-scan
#       uses: edplato/trufflehog-actions-scan@master
#       with:
#         scanArguments: "--regex --entropy=False"
#         scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json"

    - name: Install git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install
        git secrets
